using retry

diff --git a/.github/workflows/CI-CD.yml b/.github/workflows/CI-CD.yml
--- a/.github/workflows/CI-CD.yml
+++ b/.github/workflows/CI-CD.yml
@@ -51,57 +51,81 @@ jobs:
       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
+    - name: Retry Step Template
+      id: retry-step
+      run: |
+        retry() {
+          local retries=$1
+          shift
+          local count=0
+          until "$@"; do
+            exit=$?
+            count=$((count + 1))
+            if [ $count -lt $retries ]; then
+              echo "Retry $count/$retries:"
+              sleep 10
+            else
+              echo "Failed after $count attempts."
+              return $exit
+            fi
+          done
+          return 0
+        }
+    - name: Cache .NET packages
+      uses: actions/cache@v3
+      with:
+        path: ~/.nuget/packages
+        key: ${{ runner.os }}-nuget
+        restore-keys: |
+          ${{ runner.os }}-nuget
 
-      - name: Cache .NET packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.nuget/packages
-          key: ${{ runner.os }}-nuget
-          restore-keys: |
-            ${{ runner.os }}-nuget
-
-      - name: Set up .NET
-        uses: actions/setup-dotnet@v1
-        with:
-          dotnet-version: 8.x.x
+    - name: Set up .NET
+      uses: actions/setup-dotnet@v1
+      with:
+        dotnet-version: 8.x.x
       
-      - name: Set up JDK 17
-        uses: actions/setup-java@v3
-        with:
-          java-version: 17
-          distribution: 'zulu' # Alternative distribution options are available.
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
-      - name: Cache SonarCloud packages
-        uses: actions/cache@v3
-        with:
-          path: ~\sonar\cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache SonarCloud scanner
-        id: cache-sonar-scanner
-        uses: actions/cache@v3
-        with:
-          path: .\.sonar\scanner
-          key: ${{ runner.os }}-sonar-scanner
-          restore-keys: ${{ runner.os }}-sonar-scanner
-      - name: Install SonarCloud scanner
-        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
-        shell: powershell
-        run: |
-          New-Item -Path .\.sonar\scanner -ItemType Directory
-          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
-      - name: Build and analyze
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        shell: powershell
-        run: |
-          .\.sonar\scanner\dotnet-sonarscanner begin /k:"programador-tv_monorepo2" /o:"programador-tv" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
-          dotnet build
-          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
-           .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
+    - name: Set up JDK 17
+      uses: actions/setup-java@v3
+      with:
+        java-version: 17
+        distribution: 'zulu' # Alternative distribution options are available.
+        
+    - uses: actions/checkout@v3
+      with:
+        fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
+        
+    - name: Cache SonarCloud packages
+      uses: actions/cache@v3
+      with:
+        path: ~\sonar\cache
+        key: ${{ runner.os }}-sonar
+        restore-keys: ${{ runner.os }}-sonar
+        
+    - name: Cache SonarCloud scanner
+      id: cache-sonar-scanner
+      uses: actions/cache@v3
+      with:
+        path: .\.sonar\scanner
+        key: ${{ runner.os }}-sonar-scanner
+        restore-keys: ${{ runner.os }}-sonar-scanner
+        
+    - name: Install SonarCloud scanner
+      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
+      shell: powershell
+      run: |
+        New-Item -Path .\.sonar\scanner -ItemType Directory
+        dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
+        
+    - name: Build and analyze
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+      shell: powershell
+      run: |
+        .\.sonar\scanner\dotnet-sonarscanner begin /k:"programador-tv_monorepo2" /o:"programador-tv" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
+        dotnet build
+        dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
+        .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
 
   publish_api:
     name: Deploy Core.WebAPI
@@ -115,17 +139,13 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-api
-           docker-compose -f docker-compose.prod.yml push core-api
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-api
-          docker-compose -f docker-compose.yml push core-api
-         else  
-          docker-compose -f docker-compose.yml build core-api
-         fi
+        retry 3 docker-compose -f docker-compose.prod.yml build core-api
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-api
 
   publish_websocket:
     name: Deploy Core.WebSocket
@@ -139,17 +159,13 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-websocket
-           docker-compose -f docker-compose.prod.yml push core-websocket
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-websocket
-          docker-compose -f docker-compose.yml push core-websocket
-         else  
-          docker-compose -f docker-compose.yml build core-websocket
-         fi
+        retry 3 docker-compose -f docker-compose.prod.yml build core-websocket
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-websocket
 
   publish_background:
     name: Deploy Core.Background
@@ -163,17 +179,13 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-background
-           docker-compose -f docker-compose.prod.yml push core-background
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-background
-          docker-compose -f docker-compose.yml push core-background
-         else  
-          docker-compose -f docker-compose.yml build core-background
-         fi
+        retry 3 docker-compose -f docker-compose.prod.yml build core-background
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-background
          
   publish_background_live:
     name: Deploy Core.Background.Live
@@ -187,17 +199,13 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-background-live
-           docker-compose -f docker-compose.prod.yml push core-background-live
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-background-live
-          docker-compose -f docker-compose.yml push core-background-live
-         else  
-          docker-compose -f docker-compose.yml build core-background-live
-         fi     
+        retry 3 docker-compose -f docker-compose.prod.yml build core-background-live
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-background-live
          
   publish_background_browser:
     name: Deploy Core.Background.Browser
@@ -211,18 +219,14 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-background-browser
-           docker-compose -f docker-compose.prod.yml push core-background-browser
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-background-browser
-          docker-compose -f docker-compose.yml push core-background-browser
-         else  
-          docker-compose -f docker-compose.yml build core-background-browser
-         fi     
-
+        retry 3 docker-compose -f docker-compose.prod.yml build core-background-browser
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-background-browser
+     
   publish_rtmp_live:
     name: Deploy Core.RTMP.Live
     runs-on: ubuntu-latest
@@ -235,17 +239,13 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build core-rtmp-live
-           docker-compose -f docker-compose.prod.yml push core-rtmp-live
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build core-rtmp-live
-          docker-compose -f docker-compose.yml push core-rtmp-live
-         else  
-          docker-compose -f docker-compose.yml build core-rtmp-live
-         fi   
+        retry 3 docker-compose -f docker-compose.prod.yml build core-rtmp-live
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push core-rtmp-live
 
   publish_app_platform:
     name: Deploy Core.APP.Platform
@@ -259,15 +259,10 @@ jobs:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
-    - name: Build and push Docker image
+    - name: Build Docker image
       run: |
-         if [ ${{ github.ref }} = 'refs/heads/main' ]; then
-           docker-compose -f docker-compose.prod.yml build platform
-           docker-compose -f docker-compose.prod.yml push platform
-         elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
-          docker-compose -f docker-compose.yml build platform
-          docker-compose -f docker-compose.yml push platform
-         else  
-          docker-compose -f docker-compose.yml build platform
-         fi   
-
+        retry 3 docker-compose -f docker-compose.prod.yml build platform
+    - name: Publish Docker image
+      if: github.ref == 'refs/heads/main'
+      run: |
+        retry 3 docker-compose -f docker-compose.prod.yml push platform
